### ISSUE TITLE
It is possible not get updates for packages if it was updated less 1 hour ago?

### ISSUE THREAD

**Issue by stepanselyuk** [fxpio/composer-asset-plugin#105]
Hello!
It is possible not get updates for packages if it was updated less 1 hour ago?

Example: I have over 150 bower packages in composer.json and every update take about 20 minutes. When I got an error, example for bad dependence, I need to start again I wait other 20 minutes, when composer/plugin get new headers and so on. How set to not touch already updated packages less sometime ago?

Thanks!

**Comment by francoispluchino** [comment]
It's possible, but if this list is cached, it will be problematic, because the VCS repository will get the local version, not the version updated during 1 hour. It would be more interesting to create a configuration in an external file (and not in composer.json extra section).

**Comment by schmunk42** [comment]
@stepanselyuk Could you share the list?

**Comment by francoispluchino** [comment]
I close this issue, because the performances have been optimized since.
