### ISSUE TITLE
Proposal: Cache timestamp value to shorten composer updates

### ISSUE THREAD

**Issue by schmunk42** [fxpio/composer-asset-plugin#116]
While looking at the verbose output of `composer update` I came across an idea to shorten download time and I'd like to hear your thoughts about it.

This is the output of an asset package update:

```
Downloading https://bower.herokuapp.com/packages/bootstrap
Writing /Users/tobias/.composer/cache/repo/https---bower.herokuapp.com-packages/bootstrap-3c71cc99d2fc1c12a3d3e1b27e448ca612a89a1d-package.json into cache
Adding VCS repository bower-asset/bootstrap
Downloading https://api.github.com/repos/twbs/bootstrap
Downloading https://api.github.com/repos/twbs/bootstrap/contents/bower.json?ref=master
Downloading https://api.github.com/repos/twbs/bootstrap/commits/master
Downloading https://api.github.com/repos/twbs/bootstrap/tags?per_page=100
Downloading https://api.github.com/repos/twbs/bootstrap/git/refs/heads?per_page=100
Reading bower.json of bower-asset/bootstrap (v3.3.4)
Reading /Users/tobias/.composer/cache/repo/github.com/twbs/bootstrap/bower-a10eb60bc0b07b747fa0c4ebd8821eb7307bd07f from cache
Importing tag v3.3.4 (3.3.4.0)
```

The [first URL](https://api.github.com/repos/twbs/bootstrap) contains a JSON response with `updated_at` and `pushed_at`.

```
{
  "id": 2126244,
  "name": "bootstrap",
  "full_name": "twbs/bootstrap",

[...]  

  "updated_at": "2015-05-19T17:38:39Z",
  "pushed_at": "2015-05-19T10:08:18Z",

[...]  

}
```

At the moment the plugin always queries the four URLs afterwards, even if they should be already available in the local cache.

But this could be skipped, if we would set a cache entry, with the `updated_at` (or pushed) date from the JSON.
And compare this cache entry with the value from the the first request of the next `composer update`.

WDYT?

**Comment by francoispluchino** [comment]
It was part of my leads to improve performance, but alas, this is the case only after the first run. So yes, I'm interested for the development of this feature.

**Comment by SDKiller** [comment]
:+1: 
Great idea.

But as for `updated_at` - if you look at repo's 'Last updated' in Github web interface - I suppose it is something virtual, it probably can be the date of last issue creation, or milestone modification or any other activity - not only commits.

Maybe `pushed_at` is worth investigation.

**Comment by francoispluchino** [comment]
We must consider the creation of tags and branchs, so I don't know if `pushed_at` is sufficient.

**Comment by schmunk42** [comment]
If an update to tags is reflected in `pushed_at` along with changes made through the web-interface, we'd be good to go, I think.
I haven't investigated BitBucket or other APIs, but even GitHub only would be a great start.

Where is the point in the code, where this should be implemented?
I am not experienced with Symfony Apps, speaking in Yii terms, I'd create a `cacheDependency` and store the first URL as key in the cache component of the application.

**Comment by francoispluchino** [comment]
@schmunk42 here: https://github.com/francoispluchino/composer-asset-plugin/blob/master/Repository/Vcs/GitHubDriver.php

**Comment by schmunk42** [comment]
pushed_at looks good so far:

https://api.github.com/repos/schmunk42/github-api-tests

```
initial commit via web

  "created_at": "2015-05-19T18:51:31Z",
  "updated_at": "2015-05-19T18:51:31Z",
  "pushed_at": "2015-05-19T18:51:54Z",
  
web edit  
  
  "created_at": "2015-05-19T18:51:31Z",
  "updated_at": "2015-05-19T18:51:31Z",
  "pushed_at": "2015-05-19T18:53:21Z",
  
web release draft

  "created_at": "2015-05-19T18:51:31Z",
  "updated_at": "2015-05-19T18:51:31Z",
  "pushed_at": "2015-05-19T18:53:58Z",
  
push from client

  "created_at": "2015-05-19T18:51:31Z",
  "updated_at": "2015-05-19T18:51:31Z",
  "pushed_at": "2015-05-19T18:55:15Z",
  
push tag from client

  "created_at": "2015-05-19T18:51:31Z",
  "updated_at": "2015-05-19T18:51:31Z",
  "pushed_at": "2015-05-19T18:56:51Z",      
```

Anything else to test?

**Comment by francoispluchino** [comment]
- Create/Rename/Delete branches
- Create/Rename/Delete tags

**Comment by schmunk42** [comment]
```
tag delete

  "created_at": "2015-05-19T18:51:31Z",
  "updated_at": "2015-05-19T18:51:31Z",
  "pushed_at": "2015-05-19T19:02:20Z",

branch create/push

  "created_at": "2015-05-19T18:51:31Z",
  "updated_at": "2015-05-19T18:51:31Z",
  "pushed_at": "2015-05-19T19:03:05Z",

branch rename

  "created_at": "2015-05-19T18:51:31Z",
  "updated_at": "2015-05-19T18:51:31Z",
  "pushed_at": "2015-05-19T19:04:05Z",
```

**Comment by schmunk42** [comment]
What's about the `infoCache` [here](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Repository/Vcs/GitHubDriver.php#L33)?

Shouldn't it be already cached? Or is the cache not persistent between composer update runs?

From looking at the code I don't understand why there's one round (of five) requests made, but older tag seem to be cached correctly.

**Comment by francoispluchino** [comment]
`$this->infoCache`: it's a execution cache, not a file cache. The list of branches and tags are not cached in file system, but only in execution. But each file of json packages are retrieved and are cached on file system.

**Comment by francoispluchino** [comment]
Also, the content of root package json file is not cached on file system, because it can change, but with your proposal, we can put the content of root package in the cache.

**Comment by khromov** [comment]
Excellent suggestion, we use well over 30 packages at work and running `composer update`is a huge pain. 99% of the time is spent waiting for GitHub API calls to finish..

**Comment by schmunk42** [comment]
> Also, the content of root package json file is not cached on file system, because it can change, but with your proposal, we can put the content of root package in the cache.

Would it then be sufficient to just cache the root package contents? Where is the root package data fetched?

Btw, if someone is able to create a PR - don't hesitate!

**Comment by francoispluchino** [comment]
Everything starts from [AssetVcsRepository::initialize()](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Repository/AssetVcsRepository.php#L35).

And content is retrieved by the VCS Drivers: `VcsDriver::getComposerInformation($identifier)`, `VcsDriver::getTags()`, `VcsDriver::getBranches()`.

For example, for Github: [GithubDriver::getComposerInformation()](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Repository/Vcs/GitHubDriver.php#L27), [GithubDriver::getTags()](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Repository/Vcs/AbstractGitHubDriver.php#L185), [GithubDriver::getBranches()](https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitHubDriver.php#L201).

Currently, only the identifiers with SHA1 keys are cached in file system.

**Comment by schmunk42** [comment]
Can be closed due to https://github.com/francoispluchino/composer-asset-plugin/issues/226 IMO

**Comment by schmunk42** [comment]
Please reopen if needed.
