### ISSUE TITLE
recent version (1.1.2) seems to be having problem resolving requirementa

### ISSUE THREAD

**Issue by kminooie** [fxpio/composer-asset-plugin#202]
I do have latest fxp/composer-aset-plugin (v1.1.2) but when I try to force jquery 1.11 in my YII2  project by adding this line 
"bower-asset/jquery": "1.11.*@stable" 
to composer.json file, I end up getting this error:

> Your requirements could not be resolved to an installable set of packages.
>
> Problem 1
>    - The requested package bower-asset/jquery could not be found in any version, there may be a typo in the package name.
>  Problem 2
>   - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
>    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
>    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
>    - Installation request for yiisoft/yii2 >=2.0.6 -> satisfiable by yiisoft/yii2[2.0.6, 2.0.7].

This used to work before, I don't know if it is the recent updates in composer or in fxp/composer-asset-plugin but it has stopped working. 

my current composer version is "Composer version 1.0-dev (e8abc90b923250527a2d68712b663f0f41790594) 2016-03-09 11:44:27"

**Comment by Nayjest** [comment]
I have same issue. Yesterday it worked fine, today can't update anything. For npm packages same situation.

**Comment by cebe** [comment]
forcing a downgrade when you have already installed packages does not work. this is an optimization that makes the plugin a lot faster and is documented here: https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/faqs.md#composer-throws-an-exception-stating-that-the-version-does-not-exist

**Comment by Nayjest** [comment]
@cebe Tried all, does not helps. For new packages same. I added first random dependency from bower ("bower-asset/tfeslee-temp": "*") and got:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/tfeslee-temp could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

"min-stability: dev" does not helps too.
