### ISSUE TITLE
The "https://bower.herokuapp.com/packages/search/XY" file could not be downloaded (HTTP/1.1 404 Not Found)

### ISSUE THREAD

**Issue by norbe** [fxpio/composer-asset-plugin#204]
Hi,

we are using this plugin shortly and from today I'm not able to update or install any package becouse of 404 error:

  [Composer\Downloader\TransportException]
  The "https://bower.herokuapp.com/packages/search/responsivefilemanager" file could not be downloaded (HTTP/1.1 404 Not Found)

Is there some way how to prevent search on heroku? It's totally useless as we have specified our url for repository...

Our simplified composer.json:

```
    "require": {
        ...
        "bower-asset/ResponsiveFilemanager": "dev-master"
    },
    "extra": {
            "asset-installer-paths": {
                "bower-asset-library": "public/components"
            },
        "asset-repositories": [ {
            "type": "bower-git",
            "url": "git://github.com/jkocour/ResponsiveFilemanager",
            "name": "bower-asset/ResponsiveFilemanager"
        },
```

**Comment by aviator-ua** [comment]
The same error. Looks like bower search engine case sensitive again.

**Comment by norbe** [comment]
Today it works again.

But it do not change anythink that I do not understand why it is searched on bower sites if I have specified repository url and why is not 404 status handled correctly (it should continue with resolving). But I'm not sure, is it problem of this plugin or composer itself?

**Comment by francoispluchino** [comment]
@norbe Because it's the standard behavior of the VCS Drivers.
