### ISSUE TITLE
Unable to download Dependency

### ISSUE THREAD

**Issue by tschechniker** [fxpio/composer-asset-plugin#209]
Hi,

i want do download bootstrap via bower. Composer says "Your requirements could not be resolved to an installable set of packages."

Here is the debug log:

Downloading https://bower.herokuapp.com/packages/bootstrap using proxy
Writing C:\xampp\Composer/cache/repo/https---bower.herokuapp.com-packages/bootstrap-3c71cc99d2fc1c12a3d3e1b27e448ca612a89a1d-package.json into cache
Adding VCS repository bower-asset/bootstrap
Downloading https://api.github.com/repos/twbs/bootstrap using proxy
Downloading https://github.com/twbs/bootstrap using proxy
Downloading https://api.github.com/repos/twbs/bootstrap using proxy
Resolving dependencies through SAT
Dependency resolution completed in 11.383 seconds
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package bower-asset/bootstrap could not be found in any vers
ion, there may be a typo in the package name.

Potential causes:

    A typo in the package name
    The package is not available in a stable-enough version according to your min imum-stability setting see https://getcomposer.org/doc/04-schema.md#minimum-stability for more det ails.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further commo
n problems.

As you can see the plugin itself is working but i don' know why this error occours

Composer version: 1.0.0
Plugin version: 1.1.3

Composer.json:

{
"require"
{
"bower-asset/bootstrap": "3.3.6"
}
}

Thanks for your help

**Comment by francoispluchino** [comment]
Plugin is installed in global mode?

**Comment by francoispluchino** [comment]
No response from you, I close.
