### ISSUE TITLE
Installation in project scope

### ISSUE THREAD

**Issue by hypeJunction** [fxpio/composer-asset-plugin#223]
I am bit confused: the docs say you can install composer-asset-plugin in project scope, however the release notes suggest `Installation: must be do in global mode`.
So, which one is true? I have tried to move our project to project scope installation, but Travis have failed on all occasions. Local installation is succeeding (but I already have 1.1.4 installed in global scope). Is there a specific flow we should follow?
https://github.com/Elgg/Elgg/pull/9843

**Comment by francoispluchino** [comment]
Initially, it had to be the case, but unfortunately this is not possible. However I will clean the doc, it is an oversight.

**Comment by hypeJunction** [comment]
Ok, thanks for the clarification.
