### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages - when nothing has changed?

### ISSUE THREAD

**Issue by dbd5** [fxpio/composer-asset-plugin#234]
Hello,

I tried to add a package to composer.json but got the following error

Your requirements could not be resolved to an installable set of packages.    

  Problem 1
    - Conclusion: remove amilna/yii2-blog dev-master
    - Installation request for amilna/yii2-blog dev-master -> satisfiable by amilna/yii2-blog[dev-master].
    - amilna/yii2-blog dev-master requires iutbay/yii2-kcfinder dev-master -> satisfiable by iutbay/yii2-kcfinder[dev-master].
    - iutbay/yii2-kcfinder dev-master requires iutbay/yii2-fontawesome dev-master -> satisfiable by iutbay/yii2-fontawesome[dev-master].
    - iutbay/yii2-kcfinder dev-master requires iutbay/yii2-fontawesome dev-master -> satisfiable by iutbay/yii2-fontawesome[dev-master].
    - iutbay/yii2-kcfinder dev-master requires iutbay/yii2-fontawesome dev-master -> satisfiable by iutbay/yii2-fontawesome[dev-master].
    - Conclusion: don't install iutbay/yii2-fontawesome dev-master

After removing the new entry from composer.json, I have continued to get this same error message. 

All the more confusing is the fact that the analysis is cryptic. The package amilna/yii2-blog dev-master has been in my composer.json for months and I have checked, the package has not been changed for a long time.

I have updated both composer and composer-asset-plugin to the latest stable.

Please help, thanks

**Comment by francoispluchino** [comment]
Try with the `1.2.x-dev` version of this plugin.

**Comment by dbd5** [comment]
Thanks
