### ISSUE TITLE
1.2.0-beta1 release?

### ISSUE THREAD

**Issue by schmunk42** [fxpio/composer-asset-plugin#235]
Would it be possible to tag a `1.2.0-beta1` - I'd really like to use the new `no-api` option, without going directly on to `dev-master`.

These two issues are on the 1.2.0 milestone list:
- https://github.com/fxpio/composer-asset-plugin/pull/215 (this may require some work; move to 1.3?)
- https://github.com/fxpio/composer-asset-plugin/issues/227 (this is "just" docs)

**Comment by francoispluchino** [comment]
I have moved these new features into the `1.3.0` milestone.

**Comment by francoispluchino** [comment]
The [1.2.0](https://github.com/fxpio/composer-asset-plugin/releases/tag/v1.2.0) version is released.
