### ISSUE TITLE
asset-pattern-skip-version

### ISSUE THREAD

**Issue by loveorigami** [fxpio/composer-asset-plugin#240]
After ```composer global require fxp/composer-asset-plugin:^1.2.0```
 I am added in composer extra
```
"asset-pattern-skip-version": "(-build|-patch)" 
```
and run ```composer update -vv```

Now downloads all patches from bower-angular 

![001](https://cloud.githubusercontent.com/assets/98164/16797163/df341418-48ee-11e6-93b4-49186da60de8.png)

**Comment by francoispluchino** [comment]
Try with:
```
"asset-pattern-skip-version": "(-patch)" 
```

**Comment by loveorigami** [comment]
Nothing
![002](https://cloud.githubusercontent.com/assets/98164/16797410/1a726204-48f0-11e6-8c74-2eb8d252fdba.png)

downloads all tag very-very easy

**Comment by francoispluchino** [comment]
Ok, you use `github-no-api` option (I hadn't noticed on your first screenshot). `asset-pattern-skip-version`  option work only with the Github API, not with native GIT for the moment.

**Comment by loveorigami** [comment]
I am try ```false``` and ```true``` for ```github-no-api```

**Comment by rob006** [comment]
Your config is incorrect - you have this settings inside `asset-installer-paths` key.

**Comment by francoispluchino** [comment]
@rob006 It's exact. Thanks. And I say a stupidity... `asset-pattern-skip-version` work with native GIT normally.

**Comment by francoispluchino** [comment]
@loveorigami See the doc [Change/Disable the skip of versions by pattern](https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#changedisable-the-skip-of-versions-by-pattern) for the right configuration.

**Comment by loveorigami** [comment]
thanks, I am changed it. Sorry for my mistake.

**Comment by francoispluchino** [comment]
No problem.

**Comment by nadar** [comment]
In the docs is written:

```
By default, the plugin does not import the patch versions for increase dramatically performance. However, it is possible to change the pattern or to disable this feature.
```

So why do i have to set the 

```
"asset-pattern-skip-version": "(-patch)"
```

option in order to speed up the compser update process? (Before Version 1.2 patches has been disabled by default maybe?).
