### ISSUE TITLE
bower-asset/satellizer error : Could not parse version constraint >=1.3.x

### ISSUE THREAD

**Issue by DrFairy** [fxpio/composer-asset-plugin#244]
The bug is similar to this https://github.com/fxpio/composer-asset-plugin/issues/221 . At this time it's the unsupported first package's wildcard (*/x/X) version in a range: https://github.com/sahat/satellizer/blob/master/bower.json#L6
Seems to be a legal syntax ( "angular": "1.3.x - 1.5.x" ).

composer config example to reproduce this bug
{
  "minimum-stability": "dev",
  "require": {
    "fxp/composer-asset-plugin": "^1.2.0",
    "bower-asset/angular": "^1.5.9",
    "bower-asset/satellizer": "^0.15.4"
  }
}

**Comment by francoispluchino** [comment]
Fixed by 4c176fb7d5ecb7cc6e53454c824f02080a6627fe.
