### ISSUE TITLE
"bower-asset/moment" installs to "vendor/bower-asset" directory, not to "vendor/bower"

### ISSUE THREAD

**Issue by russ666** [fxpio/composer-asset-plugin#245]
Composer and plugin updated to latest versions.
Other bower plugins installs to right "vendor/bower" directory.
In `composer.json` it's look like `"bower-asset/moment": "*"`.
In `composer.lock` version of plugin has 4 numbers: `"version": "2.14.1.0"`, may be it necessary to know.
I tried to set latest version `2.14.1` directly in `composer.json`, nothing changes.

**Comment by cebe** [comment]
`vendor/bower-asset` is the default. if you want it to install to `vendor/bower` you need this config: 
https://github.com/yiisoft/yii2-app-basic/blob/c0ec50d6a53ba3ed91311438bf306db23dd8dd4a/composer.json#L51-L54

**Comment by russ666** [comment]
i have that params configured right, but problem still appears.
for now `bower-asset/bootstrap` installs to `vendor/bower-asset` too.
in `composer.lock` it has 4-numbers version too (`"version": "3.3.7.0"`).
thanks for answer, by the way)

**Comment by kittig** [comment]
I have the save problem.

I guess:
when you create-project, it read compose.json and install the bower assets in `vendor/bower`.
at the same time it creates the file composer.lock.

composer.lock dose not contain the `extra` part that configs  the asset-installer-paths.

when you use `composer install` or update, it reads composer.lock without the extra part. so it install assets in the default directory bower-assets.
