### ISSUE TITLE
Could not parse version constraint &&: Invalid version string "&&"

### ISSUE THREAD

**Issue by onman** [fxpio/composer-asset-plugin#247]
My project tries to install the dependency npm-asset/node-gyp. The error mentioned in the title appears, so nothing is installed at all.
This error is caused by the node-gyp version 0.9.6, which has the dependency 
"request": ">= 2 && <= 2.14"

Although the current version is 3.\* this old version prevents it from being installed.

You can reproduce this error with the following command line:
composer global require npm-asset/node-gyp

Seems like the && style is not supported by this plugin? Can/will this be fixed?

**Comment by francoispluchino** [comment]
Fixed by dacfc81d781fa31bed37ad385b2658a0ee014b01.

**Comment by pptyasar** [comment]
Still isuue occur
