### ISSUE TITLE
bower-asset/eve

### ISSUE THREAD

**Issue by antonmarin** [fxpio/composer-asset-plugin#248]
I have dependency on bower-asset/raphael `Reading bower.json of bower-asset/raphael (v2.2.1)`
This package depends eve, in its bower.json:
```
"dependencies": {
    "eve": "https://github.com/adobe-webplatform/eve.git#eef80ed"
  },
```
But instead using `https://github.com/adobe-webplatform/eve.git` composer tries to use `https://github.com/DmitryBaranovskiy/eve.git`
```
Reading bower.json of bower-asset/raphael (v2.2.1)
Adding VCS repository github.com/adobe-webplatform/eve.git                                                                                                        Importing tag v2.2.1 (2.2.1.0)                            
Adding VCS repository bower-asset/eve
Your GitHub credentials are required to fetch private repository metadata (https://github.com/DmitryBaranovskiy/eve.git)
```
Is it a bug or there is some my mistake?

**Comment by francoispluchino** [comment]
The short SHA is not supported. See #246.

**Comment by Tarekajaj** [comment]
Still having this issue, Updated to v1.4.1 of this plugin but still getting the same error

**Comment by zmiftah** [comment]
Any news on this? I updated it to v1.4.1, like @Tarekajaj did, but still the same
