### ISSUE TITLE
Add an option to disable composer-asset-plugin from root composer.json

### ISSUE THREAD

**Issue by nkovacs** [fxpio/composer-asset-plugin#249]
I'd like to use asset-packagist, but I have to have composer-asset-plugin installed globally for other projects, and having it installed [negates almost all of the speed benefits of asset-packagist](https://github.com/yiisoft/yii2/issues/8688#issuecomment-239797923). I can't use composer's `--no-plugins` option either.

I'd like to disable composer-asset-plugin from the project's composer.json (since that's where I have to add asset-packagist as a repository) so that I can work on both kinds of projects.

**Comment by schmunk42** [comment]
@nkovacs Can you work around that with `COMPOSER_HOME` https://getcomposer.org/doc/03-cli.md#composer-home?

**Comment by nkovacs** [comment]
Not really. I'm not in control of the environment of the developers working on the project, I can only change the project's composer.json.

**Comment by francoispluchino** [comment]
In this case, we cannot disable the plugin if env variable and Composer extra option are not possible.

**Comment by nkovacs** [comment]
Can't you make it not do anything?

**Comment by francoispluchino** [comment]
We can disable the plugin with a environment variable or an extra option in the project composer.json file.

**Comment by nkovacs** [comment]
> or an extra option in the project composer.json file.

That's exactly what I'd like (I misunderstood your comment).

**Comment by francoispluchino** [comment]
ok, with your previous comment, I thought that possibility was not possible.

**Comment by francoispluchino** [comment]
My approach for this new feature:

1. Use the global config option `config.fxp-asset.enabled` with the default value `true`
2. Override the config option with the custom option defines in the project composer file file (always with `config.fxp-asset.enabled`
3. Enable or disable the plugin

**Comment by schmunk42** [comment]
@francoispluchino What's about https://github.com/fxpio/composer-asset-plugin/issues/251 - I think it would be great if we could just disable the requests, if cache has been filled in the past x days - regarding performance.

**Comment by francoispluchino** [comment]
Added by fda53b9edbe53621d55e05f29a8e9b1095e32079.
