### ISSUE TITLE
"asset-pattern-skip-version" must be set in order to skip patches but it should be default as mentioned in the docs.

### ISSUE THREAD

**Issue by nadar** [fxpio/composer-asset-plugin#252]
Since version 1.2.\* of fxp (on Ubuntu 16.10)

```
$ composer global show
Changed current directory to /home/nadar/.composer
fxp/composer-asset-plugin v1.2.1 NPM/Bower Dependency Manager for Composer
```

I have to add the skip pattern version addition to **all my composer.json files on every project**, like this:

```
"extra": {
     "asset-pattern-skip-version": "(-build|-patch)"
},
```

otherwise it takes **almost forever** to run composer update:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Reading bower.json of bower-asset/angular (v1.4.2-patch4066)^C   
```

As i could see in the docs:

> **By default, the plugin does not import the patch** versions for increase dramatically performance. However, it is possible to change the pattern or to disable this feature.

This confuses my, cause i have to integrate it to all my projects composer.json. I already mentioned that in a comment of a closed issue: https://github.com/fxpio/composer-asset-plugin/issues/240#issuecomment-239132131

So maybe its wrong in the docs, or it does not work, or what else could be the case that i have the explicit override default settings in order to work?

**Comment by francoispluchino** [comment]
Indeed the doc is not updated.

**Comment by nadar** [comment]
So its not a mistake and i have to extend all composer.json files of all my projects, this affects all users working with the fxp plugin (all Yii2 developers). Actually the `bower-asset/angular` depencies is not even part of my project. I don't know where it comes from, maybe a depencie of the Yii2 Assets (not sure about that)

```
composer show | grep bower
bower-asset/bootstrap             v3.3.7             The most popular front-end framework for developing responsive, mobile first projects on the web.
bower-asset/jquery                2.2.4              
bower-asset/jquery.inputmask      3.2.7              jquery.inputmask is a jquery plugin which create an input mask.
bower-asset/punycode              v1.3.2             
bower-asset/typeahead.js          v0.11.1            
bower-asset/yii2-pjax             v2.0.6   
```

**Comment by schmunk42** [comment]
I'd also say that a default with

    "asset-pattern-skip-version": "(-build|-patch)"

would be the right choice.
