### ISSUE TITLE
Could not parse version constraint >=N.x. SemverConterter doesn't support wildcards in first part of range

### ISSUE THREAD

**Issue by lexeo** [fxpio/composer-asset-plugin#253]
Same issue like #244 . I tried to install some package from private repository. 
It requires [angular-ui/angular-google-maps](https://github.com/angular-ui/angular-google-maps).
But in [bower.json](https://github.com/angular-ui/angular-google-maps/blob/master/bower.json#L9) file of angular-google-maps package we can see:

```
"dependencies": {
    ...
    "lodash": "3.X - 4.X",
    ...
}

```

and that is why I got the error:
Could not parse version constraint >=3.x: Invalid version string "3.x".

So I ran [Fxp\Composer\AssetPlugin\Tests\Converter\SemverConverterTest](https://github.com/fxpio/composer-asset-plugin/blob/master/Tests/Converter/SemverConverterTest.php) and provided one more example in data-provider method. 
I expected that '3.x - 4.x' would be converted to  '>=3.0,<5.0', but it didn't:

Failed asserting that two strings are equal.
Expected :'>=3.0,<5.0'
Actual   :'>=3.x,<5.0'

Why does SemverConverter replace only second part of the range "3.x - 4.x" ?

**Comment by francoispluchino** [comment]
Fixed by 4c176fb7d5ecb7cc6e53454c824f02080a6627fe.
