### ISSUE TITLE
How to update GitHub token?

### ISSUE THREAD

**Issue by ydatech** [fxpio/composer-asset-plugin#263]
I have no idea how to update token for this plugin.. 

Please advise..

**Comment by francoispluchino** [comment]
You can see the Composer doc, in the [config section](https://getcomposer.org/doc/06-config.md#github-oauth) and [config command](https://getcomposer.org/doc/03-cli.md#config).

```
$ php composer.phar config github-oauth <token>
```

**Comment by ydatech** [comment]
@francoispluchino  Thank you..

**Comment by francoispluchino** [comment]
With pleasure!
