### ISSUE TITLE
composer require --prefer-dist fxp/composer-asset-plugin takes long time

### ISSUE THREAD

**Issue by foolishnoob** [fxpio/composer-asset-plugin#265]
I just input command `composer require --prefer-dist fxp/composer-asset-plugin:1.2.2 -vvv` and then it takes several hours , from the feedback infomation ,i found it loop to do this thing:
1.Reading bower.json of bower-asset/XXX (vXXX-patchXXX),
2.download from https://api.github.com/ of this patch's bower.json ,
3.and then  download from https://api.github.com of this patch's commit,
4.Importing tag of this patch
then patch minus 1,
and loop above
from patch 4XXX to patch 3XXX to patch 2XXX...
thank you very much.

**Comment by cebe** [comment]
see https://github.com/fxpio/composer-asset-plugin/issues/257
