### ISSUE TITLE
Installing scoped NPM packages

### ISSUE THREAD

**Issue by ischenko** [fxpio/composer-asset-plugin#266]
Good day!

Is it possible to install scoped NPM packages somehow (e.g. @angular/core)?

If the package name specified like "npm-asset/@angular/core" asset manager cannot find the package but if it is specified like "npm-asset/@angular%2fcore" then manager finds the package and downloads its metadata. But after that on the resolving dependencies step I'm getting next error:

>   Problem 1
    - The requested package npm-asset/@angular%2fcore could not be found, it looks like its name is invalid, "@%" is not allowed in package names.

I would like to install these packages without hacks if it is possible :)

**Comment by christiaangoossens** [comment]
This issue makes using Angular 2 impossible.
Could you add support for scoped NPM packages, so we can update to Angular 2?

**Comment by francoispluchino** [comment]
Added by 042cb0079cffb2e29fd7c46c42d19513a341a4de.

**Comment by ischenko** [comment]
@francoispluchino I still cannot install scoped NPM packages, I'm getting:

`  The requested package npm-asset/@angular/core could not be found, it looks like its name is invalid, "@" is not allowed in package names.
`

Or am I missing something? Thanks!

Plugin version 1.3.0, Composer version 1.4.1

**Comment by francoispluchino** [comment]
@ischenko  Read the doc [Work with the NPM scopes](https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#work-with-the-npm-scopes).

**Comment by ischenko** [comment]
@francoispluchino still cannot install it:
`The requested package npm-asset/angular--core could not be found in any version, there may be a typo in the package name.`

I've tried exact version number, wildcard, dev-master and also tried to clear cache.

**Comment by francoispluchino** [comment]
There is a bug when searching for the package in the NPM Registry when the package is directly added to composer.json. I fix it right away.

**Comment by ischenko** [comment]
@francoispluchino thank you!
