### ISSUE TITLE
Could not parse version constraint >=~2: Invalid version string "~2"

### ISSUE THREAD

**Issue by badbreze** [fxpio/composer-asset-plugin#270]
https://github.com/fxpio/composer-asset-plugin/issues/129

Like this isue we had a problem with version constraint, we're trying to use philippfrenzel/yii2fullcalendar, this package requires fullcalendar/fullcalendar but as of few hours the project owner has updated the version control of Jquery FROM:

"jquery": ">=2.0.0",
"moment": ">=2.9.0"

TO

"jquery": "2 - 3",
"moment": "^2.9.0"

How we can get a fix for this?

**Comment by simocheccoli** [comment]
I've got this error too.
@francoispluchino we tried to change your test adding to [SemverConverterTest](https://github.com/fxpio/composer-asset-plugin/blob/master/Tests/Converter/SemverConverterTest.php#L99) in getTestRanges function an item with array('2 -3').

Test failure...

**Comment by francoispluchino** [comment]
It is not the same problem as the issue #129.

`2 - 3` is converted into `>=~2,<4.0` and not `>=2.0,<4.0`. I work to solve this bug.

**Comment by francoispluchino** [comment]
Fixed by 623fe6b9bb28fa23b64efc208d53d6d3fcf84170.

**Comment by p2made** [comment]
So any special steps we should take to get your update on our systems? Are you going to release a new version?

**Comment by francoispluchino** [comment]
To update the plugin on the current branch of dev:

```
$ composer global require fxp/composer-asset-plugin:~1.3@dev
```

The stable version will arrive in very soon, see the [1.3.0 milestone](https://github.com/fxpio/composer-asset-plugin/milestone/12).
