### ISSUE TITLE
 Could not parse version constraint >=~2: Invalid version string "~2" when installing fullcalendar-scheduler

### ISSUE THREAD

**Issue by senguttuvang** [fxpio/composer-asset-plugin#277]
I encountered this issue when attempting to install fullcalendar-scheduler package.

  [UnexpectedValueException]
  Could not parse version constraint >=~2: Invalid version string "~2"

I tried several variations of the following command to workaround the version issue but nothing helps.

composer require bower-asset/fullcalendar-scheduler

**Comment by francoispluchino** [comment]
It's fixed in the `1.3.0@dev` version of this plugin (see 623fe6b9bb28fa23b64efc208d53d6d3fcf84170).

**Comment by sergeyz** [comment]
@francoispluchino it has an impact on all packages, require dev-master is not so good solution, are you able to tag new release?

**Comment by francoispluchino** [comment]
Use the `dev-master#2b652ae00f9a59e013d5359301e0bda9ec8be873` version with the SHA to lock the version. The release of the `1.3.0` version is not for tomorrow, but not in a very long time (see the [milestone](https://github.com/fxpio/composer-asset-plugin/milestone/12)).

**Comment by sergeyz** [comment]
So, I have to make a patch release with `dev-master` ref and another one for 1.3.0 release? It's not so easy in our case. We are waiting for a release for a week already. Can we tag 1.2.3 or 1.3.0 and 1.4.0 for issue in current milestone?

**Comment by francoispluchino** [comment]
Probably for the next versions but not for the `1.2` version. I will not patch and maintain a old branch just for a few days. I understand your point of view, and I also prefer to use a stable version instead of a branch, but you can consider the `1.3.x-dev` version as stable. It just lacks a feature. Thanks for your understanding.

**Comment by holtkamp** [comment]
>Thanks for your understanding.
I understand and can live with it, already happy it was fixed very quick!

Just a question though, this is where the PATCH version of [Semantic Versioning](http://semver.org/) is for, right? So ```dev-master#2b652ae00f9a59e013d5359301e0bda9ec8be873``` can be tagged as ```1.2.3``` and pronto? No need for maintenance etc? Or am I thinking too simple / missing some aspects of version management?

**Comment by sergeyz** [comment]
@holtkamp commits before the fix https://github.com/fxpio/composer-asset-plugin/compare/v1.2.2...master are not semver compatible with 1.2.3 version. Configuration was changed and looks like that is a BC, so requires major version IMO

**Comment by francoispluchino** [comment]
@holtkamp See the difference between the [v1.2.2 and v1.3.0@dev](https://github.com/fxpio/composer-asset-plugin/compare/v1.2.2...2b652ae00f9a59e013d5359301e0bda9ec8be873).

**Comment by francoispluchino** [comment]
@sergeyz YES!

**Comment by francoispluchino** [comment]
Several new features have been added, as well as the change to the configuration (with retrocompatibility and depreciation message). I can to postpone the last feature in progress to release the stable version, but I don't want to start maintaining 2 branches.

**Comment by holtkamp** [comment]
ok, understood!

**Comment by sergeyz** [comment]
@francoispluchino lets tag 1.3.0 right now and 1.4.0 once https://github.com/fxpio/composer-asset-plugin/pull/278 merged. This issue is a blocker in most cases and already took almost a month for fix.

**Comment by francoispluchino** [comment]
@sergeyz I am thinking of doing it.

**Comment by francoispluchino** [comment]
@sergeyz The [v1.3.0](https://github.com/fxpio/composer-asset-plugin/releases/tag/v1.3.0) version is released.
