### ISSUE TITLE
Satis build failure

### ISSUE THREAD

**Issue by Charius** [fxpio/composer-asset-plugin#288]
```php
php bin/satis build satis.json ../packages
PHP Fatal error:  Uncaught Error: Call to undefined method Composer\Package\RootPackage::getConfig() in /srv/jenkins-slave/.composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php:111
Stack trace:
#0 /srv/jenkins-slave/.composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php(74): Fxp\Composer\AssetPlugin\Config\ConfigBuilder::getConfigBase(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
```
with 1.3.0 version of plugin satis build fails. If I setup globally version 1.2.2 satis build is perfectly fine.
Composer version 1.4.1
php version 7.0.12

**Comment by Charius** [comment]
To solve problem I've set global require if version 1.2.2, but it would be great to have latest version of plugin...

**Comment by francoispluchino** [comment]
Your satis uses the `1.4.1` version of Composer ?

**Comment by Charius** [comment]
yes

**Comment by Charius** [comment]
I guess I should update satis and check out the behaviour

**Comment by Charius** [comment]
And yes, I pulled satis from master branch staged on commit https://github.com/composer/satis/commit/e16f2bf1eac617b8d17031c9f70ee228e5f6251d
And everything work perfect.

**Comment by Charius** [comment]
I'm closing the issue, thanks for attention :smiley:

**Comment by Charius** [comment]
Oh btw I was on https://github.com/composer/satis/commit/10439c168643bd74d76fc894d61ae3291c999aee
this commit when catched problem. Just for history
