### ISSUE TITLE
Content-Length mismatch

### ISSUE THREAD

**Issue by mnurulhuda** [fxpio/composer-asset-plugin#290]
I have tried to install composer-asset-plugin and i run :
`composer global require "fxp/composer-asset-plugin:^1.2.0"`

but the installation is failed. I get:

Installation failed, reverting ./composer.json to its original content.
  [Composer\Downloader\TransportException]
  Content-Length mismatch

How to solve my problem

**Comment by francoispluchino** [comment]
Try:
```
$ composer self-update
$ composer global remove fxp/composer-asset-plugin --no-plugins
$ composer global require fxp/composer-asset-plugin:^1.3.0 --prefer-dist
```

**Comment by mnurulhuda** [comment]
The result is same.
![result](https://cloud.githubusercontent.com/assets/16285443/24578191/c20672f6-1705-11e7-8726-dd252720ae4d.PNG)

**Comment by francoispluchino** [comment]
I have a doubt that the problem comes from my plugin. The `file_get_contents` function cannot read your `composer.json` file. What is your version of Composer?

**Comment by mnurulhuda** [comment]
Composer version 1.4.1 2017-03-10 09:29:45

**Comment by mylastof** [comment]
I have some problem :(
![composer content-length missmatch](https://cloud.githubusercontent.com/assets/2387514/24792968/4f51667c-1baa-11e7-90fa-bfaca6017b3f.JPG)

**Comment by francoispluchino** [comment]
The problem does not come from the plugin. Create an issue in the [Composer](https://github.com/composer/composer/issues) project.
