### ISSUE TITLE
Problem installation 

### ISSUE THREAD

**Issue by Pablossoo** [fxpio/composer-asset-plugin#294]
When I tried install asset plugin, gets

  - Installing fxp/composer-asset-plugin (v1.3.1): Cloning 0bfdd307d2 from cache

Installation failed, deleting ./composer.json.

  [RuntimeException]
  Failed to clone https://github.com/fxpio/composer-asset-plugin.git via https, ssh protocols, aborting.
  - https://github.com/fxpio/composer-asset-plugin.git
    Cloning into 'C:\Users\Pawe┼é\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin'...

    "git-upload-pack 'C:/Users/Pawe┼é/AppData/Local/Composer/vcs/https---github.com-fxpio-composer-asset-plugin.git'": git-upload-pack 'C:/Users/Pawe┼é/AppData/Local/Composer/vcs/https---github.com-fxpio-composer-asset-plugin.git': No

  uch file or directory
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    fatal: The remote end hung up unexpectedly
  - git@github.com:fxpio/composer-asset-plugin.git
    Cloning into 'C:\Users\Pawe┼é\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin'...

    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

where is problem?

**Comment by francoispluchino** [comment]
Your problem isn't caused by my plugin. You have a problem to clone with GIT. You answered `No` for what reason?

Otherwise, try with the option `--prefer-dist`.

**Comment by Pablossoo** [comment]
Ok, I reinstalled git and working!
