### ISSUE TITLE
Doesn't download recursive npm dependencies?

### ISSUE THREAD

**Issue by kael-shipman** [fxpio/composer-asset-plugin#295]
Hey,

Not sure if maybe I'm just doing this wrong, but I built a small test project with the following details:

```
// composer.json
{
  "name": "test/test-project",
  "require": {
     "test/test-module": "~0.1"
  },
  "repositories": [
    {
      "type": "path",
      "url": "./dev-libs/test/test-module"
    }
  ]
}
```

Then in test-module:
```
// composer.json
{
  "name": "test/test-module",
  "require": {
     "npm-asset/jquery-ui-npm": "~1.12"
  }
}
```

Here, the required `jquery-ui` npm library further requires `jquery`, but when I run a totally fresh `composer install`, I get the following vendor hierarchy:

```
./vendor
  /test
    /test-module
  /npm-asset
    /jquery-ui-npm
```

Notice: no `jquery` under `npm-asset`.

Any suggestions are appreciated.

**Comment by francoispluchino** [comment]
Because the version `1.12.1` of `jquery-ui-npm` doesn't have any dependencies... ;-) See the [package.json](https://github.com/jquery/jquery-ui/blob/c6f1735249295bb37153861aa97e5b3e38d46b02/package.json#L53) file.

**Comment by francoispluchino** [comment]
The `jquery dependency` is added in the `dev-master` see the commit jquery/jquery-ui@c1f96f11cc763cceb2dce87b1d42ce1ca1709d31.

**Comment by kael-shipman** [comment]
Ha! My bad. Sorry about that, and thanks for the quick reply! I think your plugin is totally going to save me from the woes of an overly complex package management scheme :).
