### ISSUE TITLE
Cannot install MathJax with Github submodule

### ISSUE THREAD

**Issue by ivan-redooc** [fxpio/composer-asset-plugin#296]
MathJax has a submodule:
https://github.com/mathjax/MathJax/tree/master/extensions/a11y
It seem not possible to dowload/clone mathjax in vendor dir (vendor/bower/MathJax) with its submodule in it.

```
"require":{
...
    "bower-asset/mathjax": "v2.7.0",
...
}

....

    "repositories": [
      {
        "name": "bower-asset/MathJax",
        "type": "bower-vcs",
        "url": "https://github.com/mathjax/MathJax.git"
      }
    ]
```

**Comment by cebe** [comment]
> MathJax has a submodule:

I do not see a submodule in the repo you linked, at least on their master branch, there is no .gitmodules file and github does not show a submodule.

**Comment by ivan-redooc** [comment]
I see. A collegue of mine point out that new (10 days ago!) MathJax has "Add static copy of the MathJax Accessibility Extensions at v1.2.2."  [v2.7.1](https://github.com/mathjax/MathJax/releases/tag/2.7.1) and this solve all my problems.
