### ISSUE TITLE
Unable to install browserify

### ISSUE THREAD

**Issue by cetver** [fxpio/composer-asset-plugin#300]
When attempting to install `npm-asset/browserify`, I'm getting error
```
composer require npm-asset/browserify

[RuntimeException]                                                                                                                                                                      
  Failed to execute git clone --mirror 'git+ssh://git@github.com/substack/node-browserify.git' '/home/cetver/.composer/cache/vcs/git-ssh---git-github.com-substack-node-browserify.git/'  
  Cloning into bare repository '/home/cetver/.composer/cache/vcs/git-ssh---git-github.com-substack-node-browserify.git'...                                                                
  Permission denied (publickey).                                                                                                                                                          
  fatal: Could not read from remote repository.                                                                                                                                           
  Please make sure you have the correct access rights                                                                                                                                     
  and the repository exists.    
```                                                                                                                                                          
Composer version 1.4.1 2017-03-10 09:29:45
fxp/composer-asset-plugin versions : * v1.1.4

Package installs via npm

**Comment by francoispluchino** [comment]
Update the plugin with the last version (1.3.x).

**Comment by cetver** [comment]
It has the latest version:
```
cetver@ubuntu:/tmp$ composer global update fxp/composer-asset-plugin 
Changed current directory to /home/cetver/.composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by vpassapera** [comment]
I get errors similar to this as well. It seems that this plugin is not honoring the protocol being used by the rest of composer and instead always uses git+ssh which requires a git token.

**Comment by francoispluchino** [comment]
@vpassapera For information, the plugin uses the VCS Repositories of Composer, and so, it uses the native system of management of the authorizations. The Oauth Token or Git SSH Key are required because the total of the dependencies is so high, that the limit imposed by Github is quickly exceeded.

**Comment by vpassapera** [comment]
@francoispluchino I see. Thank you!

I'll add that to build my build process then hehe.

**Comment by francoispluchino** [comment]
For more performance and use use the native git, see the doc [Use no-api option of VCS Githhub driver](https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#use-no-api-option-of-vcs-githhub-driver).

**Comment by vpassapera** [comment]
Yeah, i had already enabled that. I just didn't realize I would still need the token.

Easy enough since i'm using geerlingguy.composer in my ansible playbooks.

**Comment by vpassapera** [comment]
@francoispluchino Still seems to not be working, even with a github access token installed. I get:

```
03:18:23   No valid bower.json was found in any branch or tag of https://github.com/mouse0270/bootstrap-notify.git, could not load a package from it.  
```

Locally, a different one fails: `https://github.com/mrmrs/colors`
