### ISSUE TITLE
Add option for common dependency between npm and Bower

### ISSUE THREAD

**Issue by MrPetovan** [fxpio/composer-asset-plugin#311]
We are using the `composer-asset-plugin` with much success so far at https://github.com/friendica/friendica, seamlessly mixing npm and Bower dependencies.

However, I'm currently about to import a second time jQuery 2.2.4 because Bower packages can't see that it's already available as an `npm-asset`. Would it be feasible to add a `satisfies` option to prevent Bower to import a duplicate dependency if it's already present as an npm-asset?

Something like:
````json
{
    "config": {
        "fxp-asset": {
            "satisfies": {
                "npm-asset/jquery": "bower-asset/jquery"
            }
        }
    }
}
````

Additional information: We're using a common asset directory for both repositories.

**Comment by francoispluchino** [comment]
It will be very difficult. You can see the answer for the issue #312, and that even if we create a "package mock" for the `bower` dependencies, we're going to have trouble with the lock file, and the package installer of the Composer.

However, if you have a PR to propose, I'm interested.

**Comment by MrPetovan** [comment]
Ok, thanks, I didn't look at the code itself, I trust you about the difficulty of implementing it.
