### ISSUE TITLE
Every composer install took me like 20-40 minute having installed this plugin globally so I uninstalled it

### ISSUE THREAD

**Issue by FantomX1** [fxpio/composer-asset-plugin#313]
Every composer install took me like 20-40 minute having installed this plugin globally so I uninstalled it, the bad thing is I have no clue it was this plugin as I didn't realize it being installed globally. Affecting total performance of composer.

**Comment by francoispluchino** [comment]
If you do not use the features of the plugin in a project, the plugin is not enabled, and no performance degradation is observed. On the other hand, if you use features of this plugin, it will add native VCS Repositories of Composer, and unfortunately, this feature is not optimized at all in Composer, above all, if your constraints are wide.

**Comment by FantomX1** [comment]
thanks

**Comment by francoispluchino** [comment]
Small precision, if you want to have native performance for NPM or Yarn, use [Foxy](https://github.com/fxpio/foxy), it's the new version of the Composer Asset Plugin. It's a new project, because the compatibility is break, but you can see the issue #93 for more information.

**Comment by FantomX1** [comment]
thanks, I might give a Foxy check, because asset plugin used to be good but currently for me its a no go, so I used http://asset-packagist.org regarding bower stuff and my worries went away

**Comment by francoispluchino** [comment]
Very good service, and they use Composer Asset Plugin internally to solve dependencies.
