### ISSUE TITLE
Option to skip update?

### ISSUE THREAD

**Issue by Sarke** [fxpio/composer-asset-plugin#316]
As updating NPM and Bower dependencies are relatively slow (needs to hit many versions), I would appreciate an option when running `composer update` that skips checking the plugin updates, and only does a packagist.org update.

Many times I just want to update a specific private repo or fix the composer.lock file.  Skipping these long updates would be nice.

**Comment by brucebnu** [comment]
Nobody knows?

**Comment by brucebnu** [comment]
config.fxp-asset.git-skip-update (root-only)
The plugin can skip updating meta-data in git repositories for given amount of time, i.e. 6 hours, 3 days or 1 week.

"config": {
    "fxp-asset": {
        "git-skip-update": "2 days"
    }
}


https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/schema.md#multiple-version-of-depdendency-in-the-same-project
