### ISSUE TITLE
Error requiring jquery.

### ISSUE THREAD

**Issue by wdch-nseeley** [fxpio/composer-asset-plugin#318]
I've had this problem for ages and always managed to get past it without ever knowing how or why I got past it.

Basically, I can't consistently require jquery ~2.2.4 without an error.

`"bower-asset/jquery": "~2.2.4"`

`... no matching package found.`

I suspect its because the official jquery distribution [repository](https://github.com/jquery/jquery-dist/releases) does not place a v in front of the version numbers in its tags.

However, could the cause also be related to the sheer number of releases (over 100), requiring multiple pages of data to be downloaded?

It might be nice if anyone else could confirm the same difficulty I am having.

Anyways, for now maybe I need to give a it hash. I'll mess around.

https://github.com/jquery/jquery-dist/releases

**Comment by wdch-nseeley** [comment]
Yes, using a hash works fine. Now this only poses a problem for me when an upstream composer file requires bower's jquery by version, which never seems to work.

**Comment by francoispluchino** [comment]
The Composer plugin must be installed in global mode.

**Comment by wdch-nseeley** [comment]
Ah.  I'm not using composer in this way, and that would be why!

For anyone who needs to know:

Tags with a "v" before the version number are working fine.
Hashes are working fine.

If you want to use tags without a "v" before the version, the composer plugin must be installed in **global mode**.

Closing. Thanks for the support.
