### ISSUE TITLE
Composer uses semver.

### ISSUE THREAD

**Issue by bubach** [fxpio/composer-asset-plugin#327]
> NPM and Bower use Semver for formatting the versions, which is not the case for Composer. It is therefore necessary to perform a conversion, but it's not perfect because of the differences in operation between Semver and Composer.

This is just straight up wrong, from start to finish.  They all use correct semver. What differs is their own arbitrary syntax for comparing versions (>~...) and suffixes such as -alpha, which is not a part of the semver specification.

**Comment by cebe** [comment]
where did you find this statement?

**Comment by bubach** [comment]
There's a whole section/subpage of the readme dedicated to explaining how the conversion from "composer versioning" to semver works. It should not mention semver at all since you could just as easily make the opposite claim, when in fact none of them use "strict" semver but custom additions outside of the standard.
https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/schema.md#range-verison-conversion

**Comment by cebe** [comment]
made some changes: https://github.com/fxpio/composer-asset-plugin/pull/328
