### ISSUE TITLE
Compatibility with Composer 2.0

### ISSUE THREAD

**Issue by liborm85** [fxpio/composer-asset-plugin#333]
Composer 1.9 deprecated more than one -, . or _ character in package name. And composer 2.0 will throw error. 
In composer 2.0 cannot be used `--` notation for npm `@<vendor>` (eg. npm-asset/fullcalendar--core).

Composer 1.9 show this deprecation warning:
`Deprecation warning: require.npm-asset/fullcalendar--core is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.`

**Comment by francoispluchino** [comment]
Maybe test by replacing `--` by `-slash-` (or other?), but in any case, it will break the compatibility with the installed packages.

Example: `npm-asset/fullcalendar--core` by `npm-asset/fullcalendar-slash-core`.

It should also be tested if using the `replace` section does not also add the warning.

**Comment by filsh** [comment]
Is there any progress to solve the problem?

**Comment by liborm85** [comment]
@francoispluchino Change from `--` to `-slash-` sounds sensible. Maybe both variants could be supported, and that would resolve the incompatibility?

**Comment by francoispluchino** [comment]
Indeed, the best would be to take care of the 2 possibilities, but without futher analysis, I cannot confirm the feasibility.

**Comment by cebe** [comment]
I made an issue on composer repo to discuss this: https://github.com/composer/composer/issues/8749

**Comment by cebe** [comment]
This should be solved by https://github.com/composer/composer/pull/8767 now.

**Comment by francoispluchino** [comment]
I reopen this issue because we must update the plugin implementation for the Composer 2.0.

**Comment by francoispluchino** [comment]
Issue already created for that: #334.
