### ISSUE TITLE
Package fxp/composer-asset-plugin at version ~1.3 has a PHP requirement incompatible

### ISSUE THREAD

**Issue by toshcn** [fxpio/composer-asset-plugin#339]
[InvalidArgumentException]                                                                          
  Package fxp/composer-asset-plugin at version ~1.3 has a PHP requirement incompatible with your PHP  
   version, PHP extensions and Composer version

My php version 
PHP 7.2.33 (cli) (built: Dec  6 2020 11:31:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.33, Copyright (c) 1999-2018, by Zend Technologies

**Comment by toshcn** [comment]
my Composer version 2.0.12

**Comment by francoispluchino** [comment]
This plugin is compatible with Composer 1.x and it is not compatible with Composer 2.x. See the issue #334.
