### ISSUE TITLE
asset-installer-paths in composer.lock not work 

### ISSUE THREAD

**Issue by sheillendra** [fxpio/composer-asset-plugin#46]
This is a continuation of the https://github.com/yiisoft/yii2/issues/5083#issuecomment-57427979.

this code in composer.json : 

```
"asset-installer-paths": {
    "npm-asset-library": "vendor/npm",
    "bower-asset-library": "vendor/bower"
}
```

will change the bower-asset default directory to 'vendor/bower', and it work and success in my local PC (windows), and composer.lock resulting from the process should be the same.  but why Heroku (ubuntu) always install the library to "vendor/bower-asset" not to "vendor/bower" like in my local pc, whether Heroku wrong in translating?

**Comment by intricareruchika** [comment]
i got this error "extra.asset-installer-paths" option is deprecated,"when i am try to update composer

**Comment by francoispluchino** [comment]
@intricareruchika See the release note of the [1.3.0 version](https://github.com/fxpio/composer-asset-plugin/releases/tag/v1.3.0).

**Comment by intricareruchika** [comment]
i have this issue of kartik datepicker and i haven't write code of plugin events
my code is..
field($model, 'date_of_join')->widget(DatePicker::classname(), [ 'options' => ['placeholder' => 'Enter birth date ...'], 'name' => 'date_of_join', 'pluginOptions' => [ 'autoclose'=>true ], ----------------------------- issue is=Uncaught TypeError: Cannot set property 'dates' of undefined

**Comment by francoispluchino** [comment]
@intricareruchika Your last problem doesn't concern this composer plugin, it's just a tool to manage and install the asset dependencies. So, create an issue in the repository of your library.
