### ISSUE TITLE
Problem with package "bower-asset/blueimp-file-upload"

### ISSUE THREAD

**Issue by stepanselyuk** [fxpio/composer-asset-plugin#58]
Hello,
I have problem with package "bower-asset/blueimp-file-upload", seems the problem about ignored files.
In `blueimp-file-upload` and required packages `blueimp-canvas-to-blob`, `blueimp-load-image`, `blueimp-tmpl` I don't see any *.js files, *.css files or others. Only subdirs and files `.gitignore`, `.jshintrc`.

In package's bower.json (https://github.com/blueimp/jQuery-File-Upload) I see 

``` json
"ignore": [
"/*.*",
"/cors",
"css/demo-ie8.css",
"css/demo.css",
"css/style.css",
"js/app.js",
"js/main.js",
"server",
"test"
]
```

The `"/*.*"` in the first row related only to files in main directory, not for subdirs.

I've used the latest version of the plugin via `composer-update.sh`:

``` bash
#!/bin/bash
composer selfupdate
composer global require "fxp/composer-asset-plugin:1.0.*@dev" -vvv
composer update -vvv
```

**Comment by demisang** [comment]
I have the same problem, was solved by **removing** the folder **"/vendor"** and **"composer.lock"** file, then ```composer update```
