### ISSUE TITLE
Import too many tags ...

### ISSUE THREAD

**Issue by callmez** [fxpio/composer-asset-plugin#69]
when i want to install angular bower package, will wait long time to import tags(2000+ tags....),  
in the end is still get error.......fuxx..

```
Reading bower.json of bower-asset/angular (v1.3.1-patch3504)
...
Reading bower.json of bower-asset/angular (v1.3.1-patch3503)
...
Reading bower.json of bower-asset/angular (v1.3.1-patch3502)
...
...
...
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in phar:///Users/longzhang/www/composer.phar/src/Composer/DependencyResolver/Rule.php on line 50

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in phar:///Users/longzhang/www/composer.phar/src/Composer/DependencyResolver/Rule.php on line 50
```

Is there any way to make this fast....

the  composer settings `"bower-asset/angular": "1.2.*@stable | 1.3.*@stable"`

**Comment by xklake** [comment]
sad, bower.json of bower-asset/angular-resource took 7 hours, and now it move to patch 2769.

**Comment by xklake** [comment]
any network issue would break this.

**Comment by francoispluchino** [comment]
@xklake See the doc to filter the import and many many time.
